/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lantern_examples_EmptyApp */

#ifndef _Included_org_lantern_examples_EmptyApp
#define _Included_org_lantern_examples_EmptyApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lantern_examples_EmptyApp
 * Method:    set_asset_manager
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_lantern_examples_EmptyApp_set_1asset_1manager
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lantern_examples_EmptyApp
 * Method:    initialize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lantern_examples_EmptyApp_initialize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lantern_examples_EmptyApp
 * Method:    frame
 * Signature: (FII[I)V
 */
JNIEXPORT void JNICALL Java_org_lantern_examples_EmptyApp_frame
  (JNIEnv *, jclass, jfloat, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
