/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lantern_Lantern */

#ifndef _Included_org_lantern_Lantern
#define _Included_org_lantern_Lantern
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lantern_Lantern
 * Method:    start
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_org_lantern_Lantern_start
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
