/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lantern_examples_RasterizedTriangleApp */

#ifndef _Included_org_lantern_examples_RasterizedTriangleApp
#define _Included_org_lantern_examples_RasterizedTriangleApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lantern_examples_RasterizedTriangleApp
 * Method:    initialize
 * Signature: (Ljava/lang/Object;II)V
 */
JNIEXPORT void JNICALL Java_org_lantern_examples_RasterizedTriangleApp_initialize
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     org_lantern_examples_RasterizedTriangleApp
 * Method:    frame
 * Signature: (FII[I)V
 */
JNIEXPORT void JNICALL Java_org_lantern_examples_RasterizedTriangleApp_frame
  (JNIEnv *, jclass, jfloat, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
