/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lantern_examples_RasterizedTriangleApp */

#ifndef _Included_org_lantern_examples_RasterizedTriangleApp
#define _Included_org_lantern_examples_RasterizedTriangleApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lantern_examples_RasterizedTriangleApp
 * Method:    set_asset_manager
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_lantern_examples_RasterizedTriangleApp_set_1asset_1manager
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lantern_examples_RasterizedTriangleApp
 * Method:    initialize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lantern_examples_RasterizedTriangleApp_initialize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lantern_examples_RasterizedTriangleApp
 * Method:    frame
 * Signature: (FII[I)V
 */
JNIEXPORT void JNICALL Java_org_lantern_examples_RasterizedTriangleApp_frame
  (JNIEnv *, jclass, jfloat, jint, jint, jintArray);

/*
 * Class:     org_lantern_examples_RasterizedTriangleApp
 * Method:    on_key_down
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_org_lantern_examples_RasterizedTriangleApp_on_1key_1down
  (JNIEnv *, jclass, jshort);

#ifdef __cplusplus
}
#endif
#endif
