/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lantern_Lantern */

#ifndef _Included_org_lantern_Lantern
#define _Included_org_lantern_Lantern
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lantern_Lantern
 * Method:    initialize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lantern_Lantern_initialize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lantern_Lantern
 * Method:    frame
 * Signature: (FII[I)V
 */
JNIEXPORT void JNICALL Java_org_lantern_Lantern_frame
  (JNIEnv *, jclass, jfloat, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
