/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_lantern_rasterized_triangle_app_Graphics */

#ifndef _Included_com_android_lantern_rasterized_triangle_app_Graphics
#define _Included_com_android_lantern_rasterized_triangle_app_Graphics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_lantern_rasterized_triangle_app_Graphics
 * Method:    on_surface_created
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_lantern_rasterized_1triangle_1app_Graphics_on_1surface_1created
  (JNIEnv *, jclass);

/*
 * Class:     com_android_lantern_rasterized_triangle_app_Graphics
 * Method:    on_surface_changed
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_android_lantern_rasterized_1triangle_1app_Graphics_on_1surface_1changed
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_android_lantern_rasterized_triangle_app_Graphics
 * Method:    on_draw_frame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_lantern_rasterized_1triangle_1app_Graphics_on_1draw_1frame
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
