/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_lantern_rasterized_triangle_app_LaternRasterizedTriangleAppActivity */

#ifndef _Included_com_android_lantern_rasterized_triangle_app_LaternRasterizedTriangleAppActivity
#define _Included_com_android_lantern_rasterized_triangle_app_LaternRasterizedTriangleAppActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_lantern_rasterized_triangle_app_LaternRasterizedTriangleAppActivity
 * Method:    info
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_android_lantern_rasterized_1triangle_1app_LaternRasterizedTriangleAppActivity_info
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_android_lantern_rasterized_triangle_app_LaternRasterizedTriangleAppActivity
 * Method:    changeDir
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_android_lantern_rasterized_1triangle_1app_LaternRasterizedTriangleAppActivity_changeDir
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_android_lantern_rasterized_triangle_app_LaternRasterizedTriangleAppActivity
 * Method:    makeDir
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_android_lantern_rasterized_1triangle_1app_LaternRasterizedTriangleAppActivity_makeDir
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_android_lantern_rasterized_triangle_app_LaternRasterizedTriangleAppActivity
 * Method:    onKeyDown
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_lantern_rasterized_1triangle_1app_LaternRasterizedTriangleAppActivity_onKeyDown
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
